Add rvcon check for user in "dialout" group
If the user isn't in the dialout group, then they can't actually talk
to a ttyACM device. This provides a check and an error message instead
of just looking like screen failing.

diff --git a/scripts/rvcon b/scripts/rvcon
--- a/scripts/rvcon
+++ b/scripts/rvcon
@@ -15,6 +15,12 @@ Example usage:
 EOF
 }
 
+# Check that the user can actually access the TTY
+if [ `groups | grep -c dialout` -eq 0 ]; then
+    echo "[ERROR] User needs to be in group \"dialout\""
+    exit 1
+fi
+
 dir=$(dirname $(readlink -f $0))
 OPTIND=1
 while getopts "hf" opt; do
